In [27]:
import fastf1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

session = fastf1.get_session(2022, 'Monaco', "Q")
session.load()

laps = session.laps

core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '11', '1', '4', '63', '14', '44', '5', '31', '22', '77', '20', '3', '47', '23', '10', '18', '6', '24']

In [28]:
laps.shape

(404, 31)

In [29]:
# Column names
laps.columns.tolist()

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']

In [30]:
laps.info()

<class 'fastf1.core.Laps'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                404 non-null    timedelta64[ns]
 1   Driver              404 non-null    object
 2   DriverNumber        404 non-null    object
 3   LapTime             306 non-null    timedelta64[ns]
 4   LapNumber           404 non-null    float64
 5   Stint               404 non-null    float64
 6   PitOutTime          103 non-null    timedelta64[ns]
 7   PitInTime           101 non-null    timedelta64[ns]
 8   Sector1Time         397 non-null    timedelta64[ns]
 9   Sector2Time         383 non-null    timedelta64[ns]
 10  Sector3Time         310 non-null    timedelta64[ns]
 11  Sector1SessionTime  397 non-null    timedelta64[ns]
 12  Sector2SessionTime  383 non-null    timedelta64[ns]
 13  Sector3SessionTime  310 non-null    timedelta64[ns]
 14  SpeedI1             398 non-null    float64
 15  SpeedI2             383 non-null    float64
 16  SpeedFL             303 non-null    float64
 17  SpeedST             388 non-null    float64
 18  IsPersonalBest      404 non-null    bool
 19  Compound            404 non-null    object
 20  TyreLife            404 non-null    float64
 21  FreshTyre           404 non-null    bool
 22  Team                404 non-null    object
 23  LapStartTime        404 non-null    timedelta64[ns]
 24  LapStartDate        404 non-null    datetime64[ns]
 25  TrackStatus         404 non-null    object
 26  Position            0 non-null      float64
 27  Deleted             404 non-null    bool
 28  DeletedReason       404 non-null    object
 29  FastF1Generated     404 non-null    bool
 30  IsAccurate          404 non-null    bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 84.2+ KB

In [31]:
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:19:23.424000,LEC,16,0 days 00:02:02.245000,1.0,1.0,0 days 00:17:21.837000,NaT,0 days 00:00:41.672000,0 days 00:00:53.110000,...,True,Ferrari,0 days 00:17:21.837000,2022-05-28 14:02:22.231,1,NaN,False,,False,False
1,0 days 00:20:38.316000,LEC,16,0 days 00:01:14.892000,2.0,1.0,NaT,NaT,0 days 00:00:20.134000,0 days 00:00:35.102000,...,True,Ferrari,0 days 00:19:23.424000,2022-05-28 14:04:23.818,1,NaN,False,,False,True
2,0 days 00:22:23.959000,LEC,16,0 days 00:01:45.643000,3.0,1.0,NaT,NaT,0 days 00:00:34.902000,0 days 00:00:46.629000,...,True,Ferrari,0 days 00:20:38.316000,2022-05-28 14:05:38.710,1,NaN,False,,False,True
3,0 days 00:23:36.898000,LEC,16,0 days 00:01:12.939000,4.0,1.0,NaT,NaT,0 days 00:00:19.351000,0 days 00:00:34.263000,...,True,Ferrari,0 days 00:22:23.959000,2022-05-28 14:07:24.353,1,NaN,False,,False,True
4,0 days 00:25:17.259000,LEC,16,0 days 00:01:40.361000,5.0,1.0,NaT,NaT,0 days 00:00:27.058000,0 days 00:00:48.237000,...,True,Ferrari,0 days 00:23:36.898000,2022-05-28 14:08:37.292,1,NaN,False,,False,True

In [32]:
# Missing values per column
laps.isna().sum().sort_values(ascending=False)

Position              404
PitInTime             303
PitOutTime            301
SpeedFL               101
LapTime                98
Sector3Time            94
Sector3SessionTime     94
Sector2Time            21
Sector2SessionTime     21
SpeedI2                21
SpeedST                16
Sector1SessionTime      7
Sector1Time             7
SpeedI1                 6
Team                    0
Deleted                 0
DeletedReason           0
FastF1Generated         0
TrackStatus             0
LapStartDate            0
LapStartTime            0
Time                    0
FreshTyre               0
TyreLife                0
Compound                0
IsPersonalBest          0
Driver                  0
Stint                   0
LapNumber               0
DriverNumber            0
IsAccurate              0
dtype: int64

In [33]:
laps.groupby("Driver")["LapNumber"].count().sort_values(ascending=False)

Driver
HAM    29
VET    27
RUS    27
NOR    26
VER    25
PER    25
SAI    25
LEC    24
OCO    22
ALO    22
RIC    21
TSU    20
MAG    20
BOT    17
MSC    17
ALB    14
LAT    13
STR    11
GAS    10
ZHO     9
Name: LapNumber, dtype: int64

In [34]:
laps["Compound"].value_counts(dropna=False)

Compound
SOFT    404
Name: count, dtype: int64

In [36]:
driver_times = (
    laps.groupby("Driver")["LapTime"]
    .agg(["count", "mean", "median", "min"])
)

display(driver_times.sort_values("min"))

,count,mean,median,min
Driver,,,,
LEC,19,0 days 00:01:32.426631578,0 days 00:01:30.051500,0 days 00:01:11.376000
SAI,21,0 days 00:01:33.556095238,0 days 00:01:34.866000,0 days 00:01:11.601000
PER,19,0 days 00:01:24.375578947,0 days 00:01:13.324000,0 days 00:01:11.629000
VER,20,0 days 00:01:26.937750,0 days 00:01:13.402000,0 days 00:01:11.666000
NOR,20,0 days 00:01:28.302650,0 days 00:01:13.996000,0 days 00:01:11.849000
RUS,22,0 days 00:01:27.056500,0 days 00:01:16.628000,0 days 00:01:12.112000
ALO,15,0 days 00:01:27.369066666,0 days 00:01:13.771000,0 days 00:01:12.247000
OCO,15,0 days 00:01:28.431866666,0 days 00:01:13.592000,0 days 00:01:12.528000
HAM,22,0 days 00:01:28.267272727,0 days 00:01:25.008000,0 days 00:01:12.560000
VET,21,0 days 00:01:26.312666666,0 days 00:01:16.944000,0 days 00:01:12.613000
TSU,15,0 days 00:01:28.174866666,0 days 00:01:14.217500,0 days 00:01:12.797000
BOT,12,0 days 00:01:30.935750,0 days 00:01:13.541000,0 days 00:01:12.909000
MAG,14,0 days 00:01:25.685071428,0 days 00:01:15.902000,0 days 00:01:12.921000
RIC,16,0 days 00:01:28.199875,0 days 00:01:14.640000,0 days 00:01:12.964000
MSC,12,0 days 00:01:27.336333333,0 days 00:01:24.021000,0 days 00:01:13.081000
ALB,12,0 days 00:01:29.223500,0 days 00:01:26.228000,0 days 00:01:13.611000
GAS,7,0 days 00:01:30.468285714,0 days 00:01:21.540500,0 days 00:01:13.660000
STR,8,0 days 00:01:26.225000,0 days 00:01:15.902000,0 days 00:01:13.678000
LAT,10,0 days 00:01:27.243100,0 days 00:01:16.358000,0 days 00:01:14.403000
ZHO,6,0 days 00:01:33.223500,0 days 00:01:17.730000,0 days 00:01:15.606000