In [1]:
import fastf1
session = fastf1.get_session(2021, 7,'Q')
print(session.name)

req         WARNING 	DEFAULT CACHE ENABLED! (48.0 KB) /Users/azizmejri/Library/Caches/fastf1

Qualifying

In [2]:
print(session.date)

2021-06-19 13:00:00

In [3]:
print(session.event)

RoundNumber                                                     7
Country                                                    France
Location                                             Le Castellet
OfficialEventName    FORMULA 1 EMIRATES GRAND PRIX DE FRANCE 2021
EventDate                                     2021-06-20 00:00:00
EventName                                       French Grand Prix
EventFormat                                          conventional
Session1                                               Practice 1
Session1Date                            2021-06-18 11:30:00+02:00
Session1DateUtc                               2021-06-18 09:30:00
Session2                                               Practice 2
Session2Date                            2021-06-18 15:00:00+02:00
Session2DateUtc                               2021-06-18 13:00:00
Session3                                               Practice 3
Session3Date                            2021-06-19 12:00:00+02:00
Session3DateUtc                               2021-06-19 10:00:00
Session4                                               Qualifying
Session4Date                            2021-06-19 15:00:00+02:00
Session4DateUtc                               2021-06-19 13:00:00
Session5                                                     Race
Session5Date                            2021-06-20 15:00:00+02:00
Session5DateUtc                               2021-06-20 13:00:00
F1ApiSupport                                                 True
Name: 7, dtype: object

In [4]:
print(session.event['EventName'])

French Grand Prix

In [5]:
schedule = fastf1.get_event_schedule(2026)
print(schedule)

    RoundNumber               Country           Location  \
0             0               Bahrain            Bahrain
1             0               Bahrain            Bahrain
2             1             Australia          Melbourne
3             2                 China           Shanghai
4             3                 Japan             Suzuka
5             4         United States      Miami Gardens
6             5                Canada           Montréal
7             6                Monaco        Monte Carlo
8             7                 Spain          Barcelona
9             8               Austria          Spielberg
10            9        United Kingdom        Silverstone
11           10               Belgium  Spa-Francorchamps
12           11               Hungary           Budapest
13           12           Netherlands          Zandvoort
14           13                 Italy              Monza
15           14                 Spain             Madrid
16           15            Azerbaijan               Baku
17           16               Bahrain       Kuala Lumpur
18           17             Singapore         Marina Bay
19           18         United States             Austin
20           19                Mexico        Mexico City
21           20                Brazil          São Paulo
22           21         United States          Las Vegas
23           22                 Qatar             Lusail
24           23  United Arab Emirates         Yas Marina

                                    OfficialEventName  EventDate  \
0          FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026 2026-02-13
1          FORMULA 1 ARAMCO PRE-SEASON TESTING 2 2026 2026-02-20
2   FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ... 2026-03-08
3          FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026 2026-03-15
4           FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026 2026-03-29
5          FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026 2026-05-03
6          FORMULA 1 LENOVO GRAND PRIX DU CANADA 2026 2026-05-24
7   FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026 2026-06-07
8   FORMULA 1 MSC CRUISES GRAN PREMIO DE BARCELONA... 2026-06-14
9           FORMULA 1 LENOVO AUSTRIAN GRAND PRIX 2026 2026-06-28
10          FORMULA 1 PIRELLI BRITISH GRAND PRIX 2026 2026-07-05
11   FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2026 2026-07-19
12            FORMULA 1 AWS HUNGARIAN GRAND PRIX 2026 2026-07-26
13           FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2026 2026-08-23
14        FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026 2026-09-06
15     FORMULA 1 TAG HEUER GRAN PREMIO DE ESPAÑA 2026 2026-09-13
16  FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ... 2026-09-26
17  FORMULA 1 GULF AIR BAHRAIN GRAND PRIX IN MALAY... 2026-10-04
18  FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P... 2026-10-11
19  FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX... 2026-10-25
20  FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026 2026-11-01
21  FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU... 2026-11-08
22       FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026 2026-11-21
23      FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026 2026-11-29
24  FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ... 2026-12-06

                   EventName        EventFormat    Session1  \
0         Pre-Season Testing            testing  Practice 1
1         Pre-Season Testing            testing  Practice 1
2      Australian Grand Prix       conventional  Practice 1
3         Chinese Grand Prix  sprint_qualifying  Practice 1
4        Japanese Grand Prix       conventional  Practice 1
5           Miami Grand Prix  sprint_qualifying  Practice 1
6        Canadian Grand Prix  sprint_qualifying  Practice 1
7          Monaco Grand Prix       conventional  Practice 1
8       Barcelona Grand Prix       conventional  Practice 1
9        Austrian Grand Prix       conventional  Practice 1
10        British Grand Prix  sprint_qualifying  Practice 1
11        Belgian Grand Prix       conventional  Practice 1
12      Hungarian Grand Prix       conventional  Practice 1
13          Dutch Grand Prix  sprint_qualifying  Practice 1
14        Italian Grand Prix       conventional  Practice 1
15        Spanish Grand Prix       conventional  Practice 1
16     Azerbaijan Grand Prix       conventional  Practice 1
17        Bahrain Grand Prix       conventional  Practice 1
18      Singapore Grand Prix  sprint_qualifying  Practice 1
19  United States Grand Prix       conventional  Practice 1
20    Mexico City Grand Prix       conventional  Practice 1
21      São Paulo Grand Prix       conventional  Practice 1
22      Las Vegas Grand Prix       conventional  Practice 1
23          Qatar Grand Prix       conventional  Practice 1
24      Abu Dhabi Grand Prix       conventional  Practice 1

                 Session1Date     Session1DateUtc  ...    Session3  \
0   2026-02-11 10:00:00+03:00 2026-02-11 07:00:00  ...  Practice 3
1   2026-02-18 10:00:00+03:00 2026-02-18 07:00:00  ...  Practice 3
2   2026-03-06 12:30:00+11:00 2026-03-06 01:30:00  ...  Practice 3
3   2026-03-13 11:30:00+08:00 2026-03-13 03:30:00  ...      Sprint
4   2026-03-27 11:30:00+09:00 2026-03-27 02:30:00  ...  Practice 3
5   2026-05-01 12:00:00-04:00 2026-05-01 16:00:00  ...      Sprint
6   2026-05-22 12:30:00-04:00 2026-05-22 16:30:00  ...      Sprint
7   2026-06-05 13:30:00+02:00 2026-06-05 11:30:00  ...  Practice 3
8   2026-06-12 13:30:00+02:00 2026-06-12 11:30:00  ...  Practice 3
9   2026-06-26 13:30:00+02:00 2026-06-26 11:30:00  ...  Practice 3
10  2026-07-03 12:30:00+01:00 2026-07-03 11:30:00  ...      Sprint
11  2026-07-17 13:30:00+02:00 2026-07-17 11:30:00  ...  Practice 3
12  2026-07-24 13:30:00+02:00 2026-07-24 11:30:00  ...  Practice 3
13  2026-08-21 12:30:00+02:00 2026-08-21 10:30:00  ...      Sprint
14  2026-09-04 12:30:00+02:00 2026-09-04 10:30:00  ...  Practice 3
15  2026-09-11 13:30:00+02:00 2026-09-11 11:30:00  ...  Practice 3
16  2026-09-24 12:30:00+04:00 2026-09-24 08:30:00  ...  Practice 3
17  2026-10-02 12:30:00+08:00 2026-10-02 04:30:00  ...  Practice 3
18  2026-10-09 16:30:00+08:00 2026-10-09 08:30:00  ...      Sprint
19  2026-10-23 12:30:00-05:00 2026-10-23 17:30:00  ...  Practice 3
20  2026-10-30 12:30:00-06:00 2026-10-30 18:30:00  ...  Practice 3
21  2026-11-06 12:30:00-03:00 2026-11-06 15:30:00  ...  Practice 3
22  2026-11-19 16:30:00-08:00 2026-11-20 00:30:00  ...  Practice 3
23  2026-11-27 16:30:00+03:00 2026-11-27 13:30:00  ...  Practice 3
24  2026-12-04 13:30:00+04:00 2026-12-04 09:30:00  ...  Practice 3

                 Session3Date     Session3DateUtc    Session4  \
0   2026-02-13 10:00:00+03:00 2026-02-13 07:00:00        None
1   2026-02-20 10:00:00+03:00 2026-02-20 07:00:00        None
2   2026-03-07 12:30:00+11:00 2026-03-07 01:30:00  Qualifying
3   2026-03-14 11:00:00+08:00 2026-03-14 03:00:00  Qualifying
4   2026-03-28 11:30:00+09:00 2026-03-28 02:30:00  Qualifying
5   2026-05-02 12:00:00-04:00 2026-05-02 16:00:00  Qualifying
6   2026-05-23 12:00:00-04:00 2026-05-23 16:00:00  Qualifying
7   2026-06-06 12:30:00+02:00 2026-06-06 10:30:00  Qualifying
8   2026-06-13 12:30:00+02:00 2026-06-13 10:30:00  Qualifying
9   2026-06-27 12:30:00+02:00 2026-06-27 10:30:00  Qualifying
10  2026-07-04 12:00:00+01:00 2026-07-04 11:00:00  Qualifying
11  2026-07-18 12:30:00+02:00 2026-07-18 10:30:00  Qualifying
12  2026-07-25 12:30:00+02:00 2026-07-25 10:30:00  Qualifying
13  2026-08-22 12:00:00+02:00 2026-08-22 10:00:00  Qualifying
14  2026-09-05 12:30:00+02:00 2026-09-05 10:30:00  Qualifying
15  2026-09-12 12:30:00+02:00 2026-09-12 10:30:00  Qualifying
16  2026-09-25 12:30:00+04:00 2026-09-25 08:30:00  Qualifying
17  2026-10-03 12:30:00+08:00 2026-10-03 04:30:00  Qualifying
18  2026-10-10 17:00:00+08:00 2026-10-10 09:00:00  Qualifying
19  2026-10-24 12:30:00-05:00 2026-10-24 17:30:00  Qualifying
20  2026-10-31 11:30:00-06:00 2026-10-31 17:30:00  Qualifying
21  2026-11-07 11:30:00-03:00 2026-11-07 14:30:00  Qualifying
22  2026-11-20 16:30:00-08:00 2026-11-21 00:30:00  Qualifying
23  2026-11-28 17:30:00+03:00 2026-11-28 14:30:00  Qualifying
24  2026-12-05 14:30:00+04:00 2026-12-05 10:30:00  Qualifying

                 Session4Date     Session4DateUtc Session5  \
0                         NaT                 NaT     None
1                         NaT                 NaT     None
2   2026-03-07 16:00:00+11:00 2026-03-07 05:00:00     Race
3   2026-03-14 15:00:00+08:00 2026-03-14 07:00:00     Race
4   2026-03-28 15:00:00+09:00 2026-03-28 06:00:00     Race
5   2026-05-02 16:00:00-04:00 2026-05-02 20:00:00     Race
6   2026-05-23 16:00:00-04:00 2026-05-23 20:00:00     Race
7   2026-06-06 16:00:00+02:00 2026-06-06 14:00:00     Race
8   2026-06-13 16:00:00+02:00 2026-06-13 14:00:00     Race
9   2026-06-27 16:00:00+02:00 2026-06-27 14:00:00     Race
10  2026-07-04 16:00:00+01:00 2026-07-04 15:00:00     Race
11  2026-07-18 16:00:00+02:00 2026-07-18 14:00:00     Race
12  2026-07-25 16:00:00+02:00 2026-07-25 14:00:00     Race
13  2026-08-22 16:00:00+02:00 2026-08-22 14:00:00     Race
14  2026-09-05 16:00:00+02:00 2026-09-05 14:00:00     Race
15  2026-09-12 16:00:00+02:00 2026-09-12 14:00:00     Race
16  2026-09-25 16:00:00+04:00 2026-09-25 12:00:00     Race
17  2026-10-03 16:00:00+08:00 2026-10-03 08:00:00     Race
18  2026-10-10 21:00:00+08:00 2026-10-10 13:00:00     Race
19  2026-10-24 16:00:00-05:00 2026-10-24 21:00:00     Race
20  2026-10-31 15:00:00-06:00 2026-10-31 21:00:00     Race
21  2026-11-07 15:00:00-03:00 2026-11-07 18:00:00     Race
22  2026-11-20 20:00:00-08:00 2026-11-21 04:00:00     Race
23  2026-11-28 21:00:00+03:00 2026-11-28 18:00:00     Race
24  2026-12-05 18:00:00+04:00 2026-12-05 14:00:00     Race

                 Session5Date     Session5DateUtc F1ApiSupport
0                         NaT                 NaT         True
1                         NaT                 NaT         True
2   2026-03-08 15:00:00+11:00 2026-03-08 04:00:00         True
3   2026-03-15 15:00:00+08:00 2026-03-15 07:00:00         True
4   2026-03-29 14:00:00+09:00 2026-03-29 05:00:00         True
5   2026-05-03 13:00:00-04:00 2026-05-03 17:00:00         True
6   2026-05-24 16:00:00-04:00 2026-05-24 20:00:00         True
7   2026-06-07 15:00:00+02:00 2026-06-07 13:00:00         True
8   2026-06-14 15:00:00+02:00 2026-06-14 13:00:00         True
9   2026-06-28 15:00:00+02:00 2026-06-28 13:00:00         True
10  2026-07-05 15:00:00+01:00 2026-07-05 14:00:00         True
11  2026-07-19 15:00:00+02:00 2026-07-19 13:00:00         True
12  2026-07-26 15:00:00+02:00 2026-07-26 13:00:00         True
13  2026-08-23 15:00:00+02:00 2026-08-23 13:00:00         True
14  2026-09-06 15:00:00+02:00 2026-09-06 13:00:00         True
15  2026-09-13 15:00:00+02:00 2026-09-13 13:00:00         True
16  2026-09-26 15:00:00+04:00 2026-09-26 11:00:00         True
17  2026-10-04 15:00:00+08:00 2026-10-04 07:00:00         True
18  2026-10-11 20:00:00+08:00 2026-10-11 12:00:00         True
19  2026-10-25 15:00:00-05:00 2026-10-25 20:00:00         True
20  2026-11-01 14:00:00-06:00 2026-11-01 20:00:00         True
21  2026-11-08 14:00:00-03:00 2026-11-08 17:00:00         True
22  2026-11-21 20:00:00-08:00 2026-11-22 04:00:00         True
23  2026-11-29 19:00:00+03:00 2026-11-29 16:00:00         True
24  2026-12-06 17:00:00+04:00 2026-12-06 13:00:00         True

[25 rows x 23 columns]

In [17]:
session = fastf1.get_session(2026, 'Singapore', 'Q')
session.load()

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 22 drivers: ['3', '16', '44', '12', '1', '63', '81', '10', '30', '41', '27', '87', '31', '55', '5', '43', '14', '23', '18', '11', '77', '6']

In [18]:
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
DriverNumber,,,,,,,,,,,,,,,,,,,,,
3,3,,VER,max_verstappen,Red Bull,,red_bull,Max,Verstappen,Max Verstappen,...,1.0,,NaN,0 days 00:01:33.241000,0 days 00:01:31.639000,0 days 00:01:31.373000,NaT,,NaN,NaN
16,16,,LEC,leclerc,Ferrari,,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,,NaN,0 days 00:01:32.774000,0 days 00:01:31.953000,0 days 00:01:31.427000,NaT,,NaN,NaN
44,44,,HAM,hamilton,Ferrari,,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:32.429000,0 days 00:01:31.529000,0 days 00:01:31.496000,NaT,,NaN,NaN
12,12,,ANT,antonelli,Mercedes,,mercedes,Andrea Kimi,Antonelli,Andrea Kimi Antonelli,...,4.0,,NaN,0 days 00:01:33.601000,0 days 00:01:32.079000,0 days 00:01:31.562000,NaT,,NaN,NaN
1,1,,NOR,norris,McLaren,,mclaren,Lando,Norris,Lando Norris,...,5.0,,NaN,0 days 00:01:32.775000,0 days 00:01:31.895000,0 days 00:01:31.712000,NaT,,NaN,NaN
63,63,,RUS,russell,Mercedes,,mercedes,George,Russell,George Russell,...,6.0,,NaN,0 days 00:01:33.617000,0 days 00:01:32.212000,0 days 00:01:31.747000,NaT,,NaN,NaN
81,81,,PIA,piastri,McLaren,,mclaren,Oscar,Piastri,Oscar Piastri,...,7.0,,NaN,0 days 00:01:33.076000,0 days 00:01:32.245000,0 days 00:01:31.860000,NaT,,NaN,NaN
10,10,,GAS,gasly,Alpine F1 Team,,alpine,Pierre,Gasly,Pierre Gasly,...,8.0,,NaN,0 days 00:01:33.182000,0 days 00:01:32.602000,0 days 00:01:32.225000,NaT,,NaN,NaN
30,30,,LAW,lawson,RB F1 Team,,rb,Liam,Lawson,Liam Lawson,...,9.0,,NaN,0 days 00:01:32.885000,0 days 00:01:32.319000,0 days 00:01:32.369000,NaT,,NaN,NaN
41,41,,LIN,arvid_lindblad,RB F1 Team,,rb,Arvid,Lindblad,Arvid Lindblad,...,10.0,,NaN,0 days 00:01:33.288000,0 days 00:01:32.498000,0 days 00:01:32.781000,NaT,,NaN,NaN
27,27,,HUL,hulkenberg,Audi,,audi,Nico,Hülkenberg,Nico Hülkenberg,...,11.0,,NaN,0 days 00:01:33.147000,0 days 00:01:32.784000,NaT,NaT,,NaN,NaN
87,87,,BEA,bearman,Haas F1 Team,,haas,Oliver,Bearman,Oliver Bearman,...,12.0,,NaN,0 days 00:01:33.356000,0 days 00:01:32.908000,NaT,NaT,,NaN,NaN
31,31,,OCO,ocon,Haas F1 Team,,haas,Esteban,Ocon,Esteban Ocon,...,13.0,,NaN,0 days 00:01:33.803000,0 days 00:01:33.323000,NaT,NaT,,NaN,NaN
55,55,,SAI,sainz,Williams,,williams,Carlos,Sainz,Carlos Sainz,...,14.0,,NaN,0 days 00:01:33.774000,0 days 00:01:33.526000,NaT,NaT,,NaN,NaN
5,5,,BOR,bortoleto,Audi,,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,15.0,,NaN,0 days 00:01:34.169000,0 days 00:01:33.658000,NaT,NaT,,NaN,NaN
43,43,,COL,colapinto,Alpine F1 Team,,alpine,Franco,Colapinto,Franco Colapinto,...,16.0,,NaN,0 days 00:01:33.261000,0 days 00:01:33.787000,NaT,NaT,,NaN,NaN
14,14,,ALO,alonso,Aston Martin,,aston_martin,Fernando,Alonso,Fernando Alonso,...,17.0,,NaN,0 days 00:01:34.223000,NaT,NaT,NaT,,NaN,NaN
23,23,,ALB,albon,Williams,,williams,Alexander,Albon,Alexander Albon,...,18.0,,NaN,0 days 00:01:34.289000,NaT,NaT,NaT,,NaN,NaN
18,18,,STR,stroll,Aston Martin,,aston_martin,Lance,Stroll,Lance Stroll,...,19.0,,NaN,0 days 00:01:34.946000,NaT,NaT,NaT,,NaN,NaN
11,11,,PER,perez,Cadillac F1 Team,,cadillac,Sergio,Pérez,Sergio Pérez,...,20.0,,NaN,0 days 00:01:35.123000,NaT,NaT,NaT,,NaN,NaN
77,77,,BOT,bottas,Cadillac F1 Team,,cadillac,Valtteri,Bottas,Valtteri Bottas,...,21.0,,NaN,0 days 00:01:35.984000,NaT,NaT,NaT,,NaN,NaN
6,6,,HAD,hadjar,Red Bull,,red_bull,Isack,Hadjar,Isack Hadjar,...,22.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN

In [24]:
session.load(laps=True, telemetry=False)

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 22 drivers: ['3', '16', '44', '12', '1', '63', '81', '10', '30', '41', '27', '87', '31', '55', '5', '43', '14', '23', '18', '11', '77', '6']

In [42]:
session = fastf1.get_session(2021, 'Singapore', 'Q')
session.load()

events      WARNING 	Correcting user input 'Singapore' to 'Hungarian Grand Prix'
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver 77: Ignoring late data for a previously processed lap.The data may contain errors (previous: 17; current 18)
_api        WARNING 	Driver 10: Ignoring late data for a previously processed lap.The data may contain errors (previous: 7; current 8)
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 47
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 47)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '11', '10', '4', '16', '31', '14', '5', '3', '18', '7', '99', '55', '22', '63', '6', '9', '47']

In [43]:
session.laps.pick_driver('VER')

/Users/azizmejri/Desktop/Box, Box - F1/.venv/lib/python3.13/site-packages/fastf1/core.py:3175: FutureWarning: pick_driver is deprecated and will be removed in a future release. Use pick_drivers instead.
  warnings.warn(("pick_driver is deprecated and will be removed"

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
36,0 days 00:21:25.686000,VER,33,NaT,1.0,1.0,0 days 00:19:26.159000,NaT,NaT,0 days 00:00:54.614000,...,True,Red Bull Racing,0 days 00:19:26.159000,2021-07-31 13:04:27.834,1,NaN,False,,False,False
37,0 days 00:22:41.900000,VER,33,0 days 00:01:16.214000,2.0,1.0,NaT,NaT,0 days 00:00:27.600000,0 days 00:00:27.066000,...,True,Red Bull Racing,0 days 00:21:25.686000,2021-07-31 13:06:27.361,1,NaN,False,,False,True
38,0 days 00:24:31.781000,VER,33,0 days 00:01:49.881000,3.0,1.0,NaT,0 days 00:24:29.322000,0 days 00:00:34.763000,0 days 00:00:36.606000,...,True,Red Bull Racing,0 days 00:22:41.900000,2021-07-31 13:07:43.575,1,NaN,False,,False,False
39,0 days 00:43:12.248000,VER,33,NaT,4.0,2.0,0 days 00:41:25.961000,NaT,NaT,0 days 00:00:43.072000,...,True,Red Bull Racing,0 days 00:24:31.781000,2021-07-31 13:09:33.456,1,NaN,False,,False,False
40,0 days 00:44:29.017000,VER,33,0 days 00:01:16.769000,5.0,2.0,NaT,NaT,0 days 00:00:27.822000,0 days 00:00:27.320000,...,True,Red Bull Racing,0 days 00:43:12.248000,2021-07-31 13:28:13.923,1,NaN,False,,False,True
41,0 days 00:46:30.295000,VER,33,0 days 00:02:01.278000,6.0,2.0,NaT,NaT,0 days 00:00:44.777000,0 days 00:00:47.677000,...,True,Red Bull Racing,0 days 00:44:29.017000,2021-07-31 13:29:30.692,1,NaN,False,,False,True
42,0 days 00:47:47.174000,VER,33,0 days 00:01:16.879000,7.0,2.0,NaT,NaT,0 days 00:00:27.800000,0 days 00:00:27.467000,...,True,Red Bull Racing,0 days 00:46:30.295000,2021-07-31 13:31:31.970,1,NaN,False,,False,True
43,0 days 00:59:09.467000,VER,33,NaT,8.0,2.0,NaT,0 days 00:49:35.560000,NaT,NaT,...,True,Red Bull Racing,0 days 00:47:47.174000,2021-07-31 13:32:48.849,125,NaN,False,,False,False
44,0 days 01:01:12.356000,VER,33,NaT,9.0,3.0,0 days 00:59:09.387000,NaT,NaT,0 days 00:00:49.688000,...,True,Red Bull Racing,0 days 00:59:09.387000,2021-07-31 13:44:11.062,1,NaN,False,,False,False
45,0 days 01:02:28.006000,VER,33,0 days 00:01:15.650000,10.0,3.0,NaT,NaT,0 days 00:00:27.430000,0 days 00:00:26.825000,...,True,Red Bull Racing,0 days 01:01:12.356000,2021-07-31 13:46:14.031,1,NaN,False,,False,True
46,0 days 01:04:11.440000,VER,33,0 days 00:01:43.434000,11.0,3.0,NaT,0 days 01:04:09.668000,0 days 00:00:37.812000,0 days 00:00:35.753000,...,True,Red Bull Racing,0 days 01:02:28.006000,2021-07-31 13:47:29.681,1,NaN,False,,False,False
47,0 days 01:14:39.605000,VER,33,NaT,12.0,4.0,0 days 01:12:36.959000,NaT,NaT,0 days 00:00:48.226000,...,True,Red Bull Racing,0 days 01:04:11.440000,2021-07-31 13:49:13.115,1,NaN,False,,False,False
48,0 days 01:15:55.589000,VER,33,0 days 00:01:15.984000,13.0,4.0,NaT,NaT,0 days 00:00:27.441000,0 days 00:00:27.057000,...,True,Red Bull Racing,0 days 01:14:39.605000,2021-07-31 13:59:41.280,1,NaN,False,,False,True
49,0 days 01:17:31.079000,VER,33,0 days 00:01:35.490000,14.0,4.0,NaT,0 days 01:17:29.296000,0 days 00:00:32.582000,0 days 00:00:34.040000,...,True,Red Bull Racing,0 days 01:15:55.589000,2021-07-31 14:00:57.264,1,NaN,False,,False,False
50,0 days 01:22:56.861000,VER,33,NaT,15.0,5.0,0 days 01:20:45.416000,NaT,NaT,0 days 00:00:47.514000,...,True,Red Bull Racing,0 days 01:17:31.079000,2021-07-31 14:02:32.754,1,NaN,False,,False,False
51,0 days 01:24:12.701000,VER,33,0 days 00:01:15.840000,16.0,5.0,NaT,NaT,0 days 00:00:27.505000,0 days 00:00:26.953000,...,True,Red Bull Racing,0 days 01:22:56.861000,2021-07-31 14:07:58.536,1,NaN,False,,False,True
52,0 days 01:26:06.844000,VER,33,NaT,17.0,5.0,NaT,0 days 01:26:06.844000,0 days 00:00:35.841000,0 days 00:00:33.982000,...,True,Red Bull Racing,0 days 01:24:12.701000,2021-07-31 14:09:14.376,1,NaN,False,,False,False

In [48]:
session.laps['Position'].isna().sum()
len(session.laps)

253

In [45]:
session.laps.groupby("Driver")["LapNumber"].count().sort_values(
    ascending=False
)

Driver
HAM    18
BOT    18
NOR    17
VER    17
LEC    17
PER    16
ALO    15
RAI    15
OCO    15
GAS    15
VET    15
RIC    13
GIO    12
STR    12
MAZ     9
LAT     8
RUS     8
TSU     8
SAI     5
Name: LapNumber, dtype: int64